structure Tokens : Tiger_TOKENS =
struct
  (* A "scaffold" structure for debugging lexers. *)

type linenum = int
type token = string
fun TYPE_INT(i,j) = "TYPE_INT " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun TYPE_STRING(i, j) = "TYPE_STRING " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun TYPE(i,j) = "TYPE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun VAR(i,j) = "VAR   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun FUNCTION(i,j) = "FUNCTION   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun BREAK(i,j) = "BREAK   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun OF(i,j) = "OF   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun END(i,j) = "END   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun IN(i,j) = "IN   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun NIL(i,j) = "NIL   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun LET(i,j) = "LET   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun DO(i,j) = "DO   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun TO(i,j) = "TO   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun FOR(i,j) = "FOR   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun WHILE(i,j) = "WHILE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun ELSE(i,j) = "ELSE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun THEN(i,j) = "THEN   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun IF(i,j) = "IF   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun ARRAY(i,j) = "ARRAY   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun ASSIGN(i,j) = "ASSIGN   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun OR(i,j) = "OR   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun AND(i,j) = "AND   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun GE(i,j) = "GE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun GT(i,j) = "GT   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun LE(i,j) = "LE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun LT(i,j) = "LT   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun NEQ(i,j) = "NEQ   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun EQ(i,j) = "EQ   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun DIVIDE(i,j) = "DIVIDE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun TIMES(i,j) = "TIMES   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun MINUS(i,j) = "MINUS   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun PLUS(i,j) = "PLUS   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun DOT(i,j) = "DOT   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun RBRACE(i,j) = "RBRACE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun LBRACE(i,j) = "LBRACE   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun RBRACK(i,j) = "RBRACK   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun LBRACK(i,j) = "LBRACK   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun RPAREN(i,j) = "RPAREN   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun LPAREN(i,j) = "LPAREN   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun SEMICOLON(i,j) = "SEMICOLON   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun COLON(i,j) = "COLON   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun COMMA(i,j) = "COMMA   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun STRING(s,i,j) = "STRING("^s^")     " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun INT(c,i,j) = "INT("^Int.toString(c)^")   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun ID(s,i,j) = "ID("^s^")     " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
fun EOF(i,j) = "EOF   " ^ Int.toString(i) ^ "   " ^ Int.toString(j)
>>>>>>> c0b050c1962e559a39fec8bf0ae0db480792096a
end
